# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Prometheus Alertmanager installation tasks
  when: prometheus_alertmanager_enabled | bool
  tags:
    - setup-all
    - setup-prometheus-alertmanager
    - install-all
    - install-prometheus-alertmanager
  block:
    - name: Validate Prometheus Alertmanager configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Prometheus Alertmanager
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Prometheus Alertmanager uninstallation tasks
  when: not prometheus_alertmanager_enabled | bool
  tags:
    - setup-all
    - setup-prometheus-alertmanager
  block:
    - name: Uninstall Prometheus Alertmanager
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
