# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed variables for Traefik labels
  ansible.builtin.fail:
    msg: |-
      Your configuration contains a variable, which now has a different name.
      Please rename all `prometheus_alertmanager_container_labels_traefik_*` variables to `prometheus_alertmanager_container_labels_metrics_*` on your configuration file (vars.yml).

      The following variables in your configuration need to be renamed: {{ lookup('ansible.builtin.varnames', '^prometheus_alertmanager_container_labels_traefik_.+', wantlist=True) | join(', ') }}
  when: "lookup('ansible.builtin.varnames', '^prometheus_alertmanager_container_labels_traefik_.+', wantlist=True) | length > 0"

- name: Fail if required Prometheus Alertmanager settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - prometheus_alertmanager_uid
    - prometheus_alertmanager_gid
    - prometheus_alertmanager_container_network

- name: Run if Traefik is enabled
  when: prometheus_alertmanager_container_labels_metrics_enabled | bool
  block:
    - name: Fail if Traefik settings required for Prometheus Alertmanager are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - prometheus_alertmanager_container_labels_metrics_hostname
